name: Generate Elixir documentation
author: lee-dohm
description: Generates documentation for an Elixir project to be published via another Action
branding:
  icon: edit
  color: green
runs:
  using: docker
  image: Dockerfile
